src/views/partials/Header.vue

Changed behavior of the sticky header.

Rp header fix

---

src/facility-hcf.ts
src/facility-zan.ts
src/facility-zdv.ts
src/facility.ts
src/links.ts
src/router/index.ts
src/types/index.d.ts
src/views/pages/Resources.vue
src/views/pages/VisitingApplication.vue

visiting application

---

src/views/pages/Resources.vue

fix resource updated date format

---

src/views/pages/Resources.vue

add sort to resources

---

src/descriptions.ts
src/facility-hcf.ts
src/facility-zan.ts
src/facility-zdv.ts
src/facility.ts
src/types/index.d.ts
src/views/pages/EventInfo.vue
src/views/pages/EventsPage.vue
src/views/pages/StaffPage.vue
src/views/partials/TeamCard.vue
src/views/partials/events/CreateEventModal.vue
src/views/partials/events/CreatePositionModal.vue
src/views/partials/roster/ControllerRoles.vue

Role Dropdown and add team roles

---

src/links.ts
src/router/index.ts
src/types/index.d.ts
src/views/pages/ActivityPage.vue

add Controller Activity page

---

yarn.lock

To resolve https://github.com/adh-partnership/frontend/security/dependabot/1

upgrade deps

---

src/views/pages/VisitingApplication.vue

Fix filter when app is handled

fix visiting app filter on response

---

src/router/index.ts
src/views/pages/Feedback.vue
src/views/pages/FeedbackView.vue

Change feedback system

---

src/types/index.d.ts
src/views/partials/roster/ControllerProfile.vue

Show roster join date

---

src/components/modal/index.ts

Standardize the modal component so we're not creating multiple vue components to define a modal.. and this will allow more standardization of look

add modal component

---

src/views/pages/EventInfo.vue
src/views/partials/events/CreateEventModal.vue

Force event start date to be before end date

---

src/facilities/zdv/views/pages/StaffingRequest.vue

Updated per the ZDV EC.
Needs to be deployed alongside <https://github.com/adh-partnership/api/pull/163>.

Updated staffing request

---

src/facility-zlc.ts

Mirrors https://github.com/adh-partnership/frontend/pull/341 to ZLC.

Enable certificationsHideNone for ZLC

---

src/facility-zdv.ts

Excluding VRC, vSTARS, and vERAM.

Update ZDV resources categories

---

src/facility-zlc.ts

Excluding VRC, vSTARS, and vERAM.
Related: https://github.com/adh-partnership/frontend/pull/374

Update ZLC resources categories

---

src/views/pages/EventInfo.vue
src/views/pages/training/TrainingNote.vue

Reverts adh-partnership/frontend#382

Revert "whitespace for event info and training notes"

---

src/facility-zdv.ts

"Misc" link to <https://vats.im/D01Maps>.

Add another static resource per AFE

---

src/facility-hcf.ts

Added Training Scheduler to Website

Added HCF Training Link

---

src/facilities/hcf/views/pages/Homepage.vue
src/facilities/hcf/views/pages/onlinecontrollerhcf.vue

Online Controller widget now display the full name and initial of the controller instead of operating initials. Also, time format changed from X+XX to X:XX. These updates are per HCF senior staff and controller suggestions

Online Controller Format Changed (HCF Specific)

---

src/facility-zkc.ts
tailwind.config.cjs

Changed to a blue. Easier on the eyes and goes with the logo

Update ZKC Colors

---

.github/workflows/run-release.yaml

I keep accidentally forgetting the "v"

For dummy user aka Raaj

---

src/views/partials/roster/ControllerActions.vue

Looks like carried over code from remove visiting. This form will always be empty when trying to add a user as its not rendered if the controller_type = "none"

Remove, removal form check

---

src/facilities/zid/views/pages/Homepage.vue
src/facility-zid.ts

Adds LOA tab back to resources view
Changes elements on the home page

ZID Homepage and Resource updates

---

src/facilities/zid/views/pages/Homepage.vue
src/facility-zid.ts

re-add LOA and update home page

---

src/facility-zdv.ts
src/facility-zlc.ts

Update ZDV and ZLC training links

---

src/facility-zlc.ts

Add new resources category to ZLC site
